function BitMapping(){this.S=0<arguments.length?this.W=this.E=this.N=!0:this.W=this.E=this.N=!1;this.Swap=function(g){try{switch(g){case "N":case "n":this.N=!0==this.N?!1:!0;break;case "E":case "e":this.E=!0==this.E?!1:!0;break;case "W":case "w":this.W=!0==this.W?!1:!0;break;case "S":case "s":this.S=!0==this.S?!1:!0}}catch(e){"undefined"!=typeof console&&console.log(e.toString())}};this.toString=function(){var g="";try{g+="[N:"+(!0==this.N?1:0)+", E:"+(!0==this.E?1:0)+", W:"+(!0==this.W?1:0)+", S:"+
(!0==this.S?1:0)+"]"}catch(e){"undefined"!=typeof console&&console.log(e.toString())}return g}}
function MazeCell(g,e){this._column=e;this._row=g;this.Visited=0;this.BackTrack=new BitMapping;this.Solution=new BitMapping;this.Borders=new BitMapping;this.Walls=2<arguments.length?new BitMapping(!0):new BitMapping;this.toString=function(){var a="";try{a+="row: "+this._row+", column: "+this._column+"\n",a+="Borders:   "+this.Borders.toString()+"\n",a+="Walls:     "+this.Walls.toString()+"\n",a+="Solution:  "+this.Solution.toString()+"\n",a+="BackTrack: "+this.BackTrack.toString()}catch(b){"undefined"!=
typeof console&&console.log(b.toString())}return a}}
function WallMap(g){this._map=g;this._arrWalls=this._map.substr(1).split("\n");this._arrWalls.pop();this.IsWall=function(e,a){try{var b=!1;"#"==("undefined"!=typeof this._arrWalls[e]?this._arrWalls[e].substr(a,1):"")&&(b=!0)}catch(d){"undefined"!=typeof console&&console.log(d.toString())}return b};this.IsBorder=function(e,a){try{var b=!1;"@"==("undefined"!=typeof this._arrWalls[e]?this._arrWalls[e].substr(a,1):"")&&(b=!0)}catch(d){"undefined"!=typeof console&&console.log(d.toString())}return b}}
function MazeMap(g,e){this.Columns="number"!==typeof e?10:Math.floor(e);this.Rows="number"!==typeof g?5:Math.floor(g);this.TotalCells=this.Columns*this.Rows;this.VisitedCells=0;this.BackTrackPercent=2<arguments.length?"number"!==typeof arguments[2]?arguments[2]:0.65:0.65;this.Algorithm=this.MazeString="";this.CellCoords=[];this.Map=[];this.Stack=[];this.JunctionStack=[];this.Init=function(a){try{a="object"!==typeof a?{}:a;var b="undefined"!==typeof a.Walls?a.Walls:!0;this.Algorithm="undefined"!==
typeof a.Algorithm?a.Algorithm:"RecursiveBackTracker";this.Stack=[];this.JunctionStack=[];for(a=0;a<this.Rows;a++){this.Map[a]=[];for(var d=0;d<this.Columns;d++)this.CellCoords.push([a,d]),this.Map[a][d]=b?new MazeCell(a,d,!0):new MazeCell(a,d),0==a&&(this.Map[a][d].Borders.N=!0),d==this.Columns-1&&(this.Map[a][d].Borders.E=!0),0==d&&(this.Map[a][d].Borders.W=!0),a==this.Rows-1&&(this.Map[a][d].Borders.S=!0)}}catch(c){"undefined"!=typeof console&&console.log(c.toString())}return this};this.DisplayString=
function(){var a="",b="",d="";try{for(var a="\n@",c=0;c<this.Columns;c++)a=this.Map[0][c].Borders.N||this.Map[0][c].Walls.N?a+(this.Map[0][c].Borders.N?"@@":"##"):a+" #";for(var d=d+(a+"\n"),f=0;f<this.Rows;f++){a="";b="@";a=this.Map[f][0].Borders.W||this.Map[f][0].Walls.W?a+(this.Map[f][0].Borders.W?"@":"#"):a+" ";for(c=0;c<this.Columns;c++)a=this.Map[f][c].Borders.E||this.Map[f][c].Walls.E?a+(this.Map[f][c].Borders.E?" @":" #"):a+"  ",b=this.Map[f][c].Borders.S||this.Map[f][c].Walls.S?b+(this.Map[f][c].Borders.S?
"@@":c==this.Columns-1?"#@":"##"):b+(c==this.Columns-1?" @":" #");d+=a+"\n"+b+"\n"}this.MazeString=d}catch(e){"undefined"!=typeof console&&console.log(e.toString())}return d};this.Generate=function(){try{switch(this.Algorithm){case "RecursiveDivision":this.RecursiveDivision();break;default:this.RecursiveBackTracker()}}catch(a){"undefined"!=typeof console&&console.log(a.toString())}return this};this.GetCell=function(a,b){var d=null;try{this.Map.length>a&&this.Map[a].length>b&&(d=this.Map[lintRow][lintColumn])}catch(c){"undefined"!=
typeof console&&console.log(c.toString())}return d};this.RecursiveBackTracker=function(){var a=Math.floor(Math.random()*this.Columns),b=Math.floor(Math.random()*this.Rows);for(this.VisitedCells=0;this.VisitedCells<this.TotalCells;)try{var d=0,c=this.Map[b][a],f=null,e=[];c.Visited+=1;2>c.Visited&&(this.VisitedCells+=1);this.Stack.push(b+","+a);!c.Borders.N&&0<b&&1>this.Map[b-1][a].Visited&&e.push(this.Map[b-1][a]);!c.Borders.E&&a<this.Columns&&1>this.Map[b][a+1].Visited&&e.push(this.Map[b][a+1]);
!c.Borders.W&&0<a&&1>this.Map[b][a-1].Visited&&e.push(this.Map[b][a-1]);!c.Borders.S&&b<this.Rows&&1>this.Map[b+1][a].Visited&&e.push(this.Map[b+1][a]);if(0<e.length){this.JunctionStack.push(b+","+a);d=Math.floor(Math.random()*e.length);try{f=e[d]}catch(g){"undefined"!=typeof console&&console.log(g.toString())}c._row!=f._row?c._row>f._row?(c.Walls.N=!1,f.Walls.S=!1):(c.Walls.S=!1,f.Walls.N=!1):c._column<f._column?(c.Walls.E=!1,f.Walls.W=!1):(c.Walls.W=!1,f.Walls.E=!1);b=f._row;a=f._column}else{var h=
null;c.BackTrack.N=c.Walls.N;c.BackTrack.E=c.Walls.E;c.BackTrack.W=c.Walls.W;c.BackTrack.S=c.Walls.S;Math.random()>this.BackTrackPercent?h=this.JunctionStack.pop().split(","):0<this.JunctionStack.length?(d=Math.floor(Math.random()*this.JunctionStack.length),h=this.JunctionStack.splice(d,1)[0].split(",")):h=["0,0"];b=parseInt(h[0]);a=parseInt(h[1])}if("number"!==typeof b||"number"!==typeof a)if(0<=this.JunctionStack.length)var k=this.JunctionStack.pop()[0].split(","),b=parseInt(k[0]),a=parseInt(k[1]);
else a=b=0}catch(l){a="";c&&(a+="\nCurrent: "+c.toString(),a+="\nVisited: "+c.Visited);h&&(a+="\nCoordinates: "+h.toString());this.Stack&&(a+="\nStack: ["+this.Stack.join("], [")+"]");this.JunctionStack&&(a+="\nJunction Stack: ["+this.JunctionStack.join("], [")+"]");"undefined"!=typeof console&&console.log(l.toString()+a);break}return this};this.RecursiveDivision=function(){var a=0,b=0;try{for(var d=0;5>d;d++)switch(a=Math.floor(Math.random()*this.Columns),b=Math.floor(Math.random()*this.Rows),Math.floor(4*
Math.random())){case 1:this.Map[b][a].Walls.N=!0;0<b&&(this.Map[b-1][a].Walls.S=!0);break;case 2:this.Map[b][a].Walls.E=!0;a<this.Columns&&(this.Map[b][a+1].Walls.W=!0);break;case 3:this.Map[b][a].Walls.W=!0;0<a&&(this.Map[b][a-1].Walls.E=!0);break;default:this.Map[b][a].Walls.S=!0,b<this.Rows&&(this.Map[b+1][a].Walls.N=!0)}}catch(c){"undefined"!=typeof console&&console.log(c.toString())}return this}};
